version: '3.7'
services:
  cds:
    image: cds:3.3.2
    volumes:
      - ./result/:/tmp/test/:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 199
        delay: 1s
        window: 10s
      resources:
        limits:
          cpus: '1'
          memory: 512M
  native:
    image: native:3.3.2
    volumes:
      - ./result/:/tmp/test/:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 199
        delay: 1s
        window: 10s
      resources:
        limits:
          cpus: '1'
          memory: 512M
  none:
    image: none:3.3.2
    volumes:
      - ./result/:/tmp/test/:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 199
        delay: 1s
        window: 10s
      resources:
        limits:
          cpus: '1'
          memory: 512M