version: '3'
services:
  openresty:
    image: openresty/openresty:1.21.4.1-0-jammy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
  web:
    image: flux_virtual:1.0.0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
  k6:
    image: grafana/k6:0.49.0
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
    volumes:
      - ./test:/scripts
      - ./output/flux_virtual:/output
    command: >
      run /scripts/get-300.js
